apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: apartment-rent-aggregator-rabbitmq
  ports:
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: web
      port: 15672
      targetPort: 15672
    - protocol: TCP
      name: metrics
      port: 15692
      targetPort: 15692
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apartment-rent-aggregator-rabbitmq
  labels:
    app: apartment-rent-aggregator-rabbitmq
spec:
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: apartment-rent-aggregator-rabbitmq
  template:
    metadata:
      labels:
        app: apartment-rent-aggregator-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: masstransit/rabbitmq:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 15692
