apiVersion: batch/v1
kind: CronJob
metadata:
  name: apartment-rent-aggregator-web-scraping-worker
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: web-scraping-worker
            image: dmitryzhomir/apartment-rent-aggregator_web-scraping-worker:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: DATA_GENERATION_STRATEGY
              value: RandomDataGenerationStrategy
          restartPolicy: OnFailure
