on:
  check_suite:
    types: [completed]
  workflow_call:
    outputs:
      new_tag:
        description: "New tag"
        value: ${{ jobs.semver.outputs.new_tag }}
  workflow_dispatch:
    inputs:
      push:
        description: "Push"
        required: false
        type: string
        default: "false"

jobs:
  semver:
    name: "Semver"
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.semver.outputs.new_tag }}

    steps:
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # v6.1
        id: semver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          default_prerelease_bump: minor
          dry_run: ${{ github.event_name != 'check_suite' && github.event.inputs.push != 'true' }}
          create_annotated_tag: true
          release_branches: ^main$
