name: "Data Provider"

on:
  push:
    branches:
      - main
    paths:
      - "DataProvider/**"
      - ".github/workflows/data_provider.yml"
      - "!DataProvider/**.md"
  pull_request:
    paths:
      - "DataProvider/**"
      - ".github/workflows/data_provider.yml"
      - "!DataProvider/**.md"
  workflow_dispatch:
    inputs:
      apply:
        description: "Deploy"
        required: false
        type: string
        default: "false"

env:
  WORKING_DIR: DataProvider

jobs:
  semver:
    uses: ./.github/workflows/_semver.yml

  ci:
    name: "CI"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup dotnet
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: "7.0.x"

      - name: Build
        run: dotnet build DataProvider.sln

      - name: Test with the dotnet CLI
        run: dotnet test DataProvider.sln

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    if: success() && (github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event.inputs.apply == 'true')
    needs: [semver, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Log in to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: dmitryzhomir/apartment-rent-aggregator_data-provider
          tags: |
            ${{ needs.semver.outputs.new_tag }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: ${{ env.WORKING_DIR }}/src
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
